import { NextPage } from "next";
import Head from "next/head";
import CartsPage from "../templates/Cart";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>dealls-technical-test</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <CartsPage />
    </>
  );
};

export default Index;
